name: Fetch Strava Data

on:
  schedule:
    - cron: "0 4,17,21 * * *" # Runs at 8:00 PM (previous day), 9:00 AM, and 1:00 PM Pacific Time daily
  workflow_dispatch: # Allows manual runs

permissions:
  contents: write # Grant write permission for pushing changes

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Strava Fetch Script
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
      run: python scripts/fetch_strava_nik.py

    - name: Copy Updated HTML to Root
      run: cp templates/action-journal.html action-journal.html

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update action-journal with latest Strava activities" || echo "No changes to commit"
        git push
